### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: '$DATAPATH$/VGGface2/train'

### ISSUE THREAD

**Issue by MarineBirch723** [NNNNAI/VGGFace2-HQ#5]
>python scripts/crop_align_vggface2_FFHQalign.py --input_dir $DATAPATH$/VGGface2/train --output_dir_ffhqalign $ALIGN_OUTDIR$ --mode ffhq --crop_size 256
input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (320, 320)
Traceback (most recent call last):
  File "scripts/crop_align_vggface2_FFHQalign.py", line 63, in <module>
    dirs = sorted(os.listdir(input_dir))
FileNotFoundError: [WinError 3] The system cannot find the path specified: '$DATAPATH$/VGGface2/train'

**Comment by NNNNAI** [comment]
replace $DATAPATH$ with the place where you place VGGFACE2 dataset . For example if you place the dataset in /home/dataset/VGGface2, the command line will be 
```
python scripts/crop_align_vggface2_FFHQalign.py --input_dir /home/dataset/VGGface2/train --output_dir_ffhqalign $ALIGN_OUTDIR$ --mode ffhq --crop_size 256
```

**Comment by MarineBirch723** [comment]
>python scripts/crop_align_vggface2_FFHQalign.py --input_dir /Documents/vggface/VGGFace2-HQ-main/VGGface2/train --output_dir_ffhqalign $ALIGN_OUTDIR$ --mode ffhq --crop_size 256
input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (320, 320)
Traceback (most recent call last):
  File "scripts/crop_align_vggface2_FFHQalign.py", line 63, in <module>
    dirs = sorted(os.listdir(input_dir))
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/Documents/vggface/VGGFace2-HQ-main/VGGface2/train'

Still it does not work
